name: hirisenet
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.12
  - pip
  - pytorch=2.5
  - torchvision
  - torchinfo
  - pytorch-cuda=12.4
  - ipywidgets
  - widgetsnbextension
  - ipykernel
  - black
  - pytest
  - nvitop
  - wandb
  - ruff
  - pip:
    - pre-commit
    - black[jupyter]
    - torchshow
    - sentencepiece
